# Use an official Python runtime as the base image
FROM python:3.7

# Set the working directory to /app
WORKDIR /app

# Copy the requirements.txt file to the container
COPY requirements.txt .

# Install the dependencies specified in the requirements.txt file
RUN pip install -r requirements.txt

# Copy the application code to the container
COPY . .

# Set the environment variable to specify the main application file
ENV FLASK_APP=app.py

# Set the environment variable to specify the Flask environment
ENV FLASK_ENV=development

# Run the Flask development server
CMD ["flask", "run", "--host=0.0.0.0"]
